In [1]:
import tensorflow as tf

In [2]:
import sys

In [3]:
print(sys.version)

3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]


In [4]:
print(tf.__version__)

2.16.1


In [5]:
#Introduction tensors
#Creating tensors tf.constant()

scalar = tf.constant(7)
scalar

2024-04-23 20:57:39.717347: I metal_plugin/src/device/metal_device.cc:1154] Metal device set to: Apple M1
2024-04-23 20:57:39.717414: I metal_plugin/src/device/metal_device.cc:296] systemMemory: 8.00 GB
2024-04-23 20:57:39.717431: I metal_plugin/src/device/metal_device.cc:313] maxCacheSize: 2.67 GB
2024-04-23 20:57:39.717787: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2024-04-23 20:57:39.717842: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [6]:
scalar.ndim #checking the dimensions

0

In [7]:
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [8]:
vector.ndim

1

In [9]:
matrix = tf.constant([[10,7],[4, 5]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 4,  5]], dtype=int32)>

In [10]:
matrix.ndim

2

In [11]:
another_matrix = tf.constant([[10. , 11.],[3. , 4.], [5. , 6.]], dtype=tf.float16)
another_matrix


<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10., 11.],
       [ 3.,  4.],
       [ 5.,  6.]], dtype=float16)>

In [12]:
another_matrix.ndim

2

In [13]:
tensor = tf.constant([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9], [10, 11, 12]],[[13, 14, 15],[16, 17, 18]]])
tensor


<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [14]:
tensor.ndim

3

In [15]:
#Creating Tensors with tf.variable()

changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])

changeable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [16]:
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [17]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [18]:
unchangeable_tensor[0].assign(11)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [19]:
#Creating Random tensors -> some abitrary size which contain random values
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3, 2))
random_1 #Output values from a Uniform Distribution (Constant Probabilty)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.75658023, -0.06854693],
       [ 0.07595028, -1.2573844 ],
       [-0.23193759, -1.8107857 ]], dtype=float32)>

In [21]:
random_2 = tf.random.Generator.from_seed(40)
random_2 = random_2.normal(shape=(3,2))
random_2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[ 0.78953624,  0.53897345],
       [-0.48535702,  0.7405527 ],
       [ 0.31662658, -1.4391748 ]], dtype=float32)>

In [22]:
random_1 == random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [34]:
not_shuffled = tf.constant([[10, 7],[3, 4],[2, 4]])
not_shuffled 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  4]], dtype=int32)>

In [23]:
not_shuffled.ndim

2

In [28]:
shuffled = tf.random.shuffle(not_shuffled, seed=42)

In [29]:
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [ 3,  4],
       [10,  7]], dtype=int32)>